import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import { registerSW } from 'virtual:pwa-register'; // <-- PWA registration
import './index.css';
import App from './App.tsx';

// Register the service worker generated by vite-plugin-pwa
registerSW({ immediate: true }); // keep SW updated without user prompts

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <App />
  </StrictMode>
);
